import type { Source } from "./types.js";

export const communitiesOverseas: Source[] = [
  {
    id: "hackernews-top",
    name: "Hacker News (Top)",
    type: "hackernews",
    category: "community-overseas",
    url: "https://hacker-news.firebaseio.com/v0",
    weight: 9,
    language: "en",
  },
  {
    id: "reddit-webdev",
    name: "r/webdev",
    type: "rss",
    category: "community-overseas",
    url: "https://www.reddit.com/r/webdev/top.rss?t=day",
    weight: 7,
    language: "en",
  },
  {
    id: "reddit-reactjs",
    name: "r/reactjs",
    type: "rss",
    category: "community-overseas",
    url: "https://www.reddit.com/r/reactjs/top.rss?t=day",
    weight: 8,
    language: "en",
  },
  {
    id: "reddit-nextjs",
    name: "r/nextjs",
    type: "rss",
    category: "community-overseas",
    url: "https://www.reddit.com/r/nextjs/top.rss?t=day",
    weight: 8,
    language: "en",
  },
  {
    id: "reddit-typescript",
    name: "r/typescript",
    type: "rss",
    category: "community-overseas",
    url: "https://www.reddit.com/r/typescript/top.rss?t=day",
    weight: 7,
    language: "en",
  },
  {
    id: "reddit-javascript",
    name: "r/javascript",
    type: "rss",
    category: "community-overseas",
    url: "https://www.reddit.com/r/javascript/top.rss?t=day",
    weight: 7,
    language: "en",
  },
  {
    id: "reddit-programming",
    name: "r/programming",
    type: "rss",
    category: "community-overseas",
    url: "https://www.reddit.com/r/programming/top.rss?t=day",
    weight: 6,
    language: "en",
  },
  {
    id: "lobsters",
    name: "Lobste.rs",
    type: "rss",
    category: "community-overseas",
    url: "https://lobste.rs/rss",
    weight: 7,
    language: "en",
  },
  {
    id: "dev-to",
    name: "DEV Community",
    type: "rss",
    category: "community-overseas",
    url: "https://dev.to/feed",
    weight: 5,
    language: "en",
  },
  // hashnode 제거 — 전체 태그 피드 미제공
  {
    id: "echo-js",
    name: "Echo JS",
    type: "rss",
    category: "community-overseas",
    url: "https://www.echojs.com/rss",
    weight: 5,
    language: "en",
  },
  {
    id: "github-trending",
    name: "GitHub Trending",
    type: "github-trending",
    category: "community-overseas",
    url: "https://github.com/trending?since=daily",
    weight: 7,
    language: "en",
  },
];
