import type { Source } from "./types.js";

export const influencersOverseas: Source[] = [
  // YouTube 인플루언서
  {
    id: "yt-theo",
    name: "Theo (t3.gg)",
    type: "youtube",
    category: "influencer-overseas",
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCbRP3c757lWg9M-U7TyEkXA",
    channelId: "UCbRP3c757lWg9M-U7TyEkXA",
    weight: 9,
    language: "en",
  },
  {
    id: "yt-fireship",
    name: "Fireship",
    type: "youtube",
    category: "influencer-overseas",
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCsBjURrPoezykLs9EqgamOA",
    channelId: "UCsBjURrPoezykLs9EqgamOA",
    weight: 9,
    language: "en",
  },
  {
    id: "yt-jack-herrington",
    name: "Jack Herrington",
    type: "youtube",
    category: "influencer-overseas",
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UC6vRUjYqDuoUsYsku86Lrsw",
    channelId: "UC6vRUjYqDuoUsYsku86Lrsw",
    weight: 8,
    language: "en",
  },
  {
    id: "yt-webdevsimplified",
    name: "Web Dev Simplified",
    type: "youtube",
    category: "influencer-overseas",
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCFbNIlppjAuEX4znoulh0Cw",
    channelId: "UCFbNIlppjAuEX4znoulh0Cw",
    weight: 7,
    language: "en",
  },
  {
    id: "yt-kevin-powell",
    name: "Kevin Powell (CSS)",
    type: "youtube",
    category: "influencer-overseas",
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCJZv4d5_CbQ2dFSQ_MdkWog",
    channelId: "UCJZv4d5_CbQ2dFSQ_MdkWog",
    weight: 7,
    language: "en",
  },
  {
    id: "yt-matt-pocock",
    name: "Matt Pocock (TypeScript)",
    type: "youtube",
    category: "influencer-overseas",
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCswG6FSbgZjbWtdf_hMLaow",
    channelId: "UCswG6FSbgZjbWtdf_hMLaow",
    weight: 8,
    language: "en",
  },
  {
    id: "yt-primeagen",
    name: "ThePrimeagen",
    type: "youtube",
    category: "influencer-overseas",
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UC8ENHE5xdFSwx71u3fDH5Xw",
    channelId: "UC8ENHE5xdFSwx71u3fDH5Xw",
    weight: 8,
    language: "en",
  },
  {
    id: "yt-traversy",
    name: "Traversy Media",
    type: "youtube",
    category: "influencer-overseas",
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UC29ju8bIPH5as8OGnQzwJyA",
    channelId: "UC29ju8bIPH5as8OGnQzwJyA",
    weight: 6,
    language: "en",
  },
  {
    id: "yt-lee-robinson",
    name: "Lee Robinson",
    type: "youtube",
    category: "influencer-overseas",
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCZMli3czZnd1uoc1ShTouQw",
    channelId: "UCZMli3czZnd1uoc1ShTouQw",
    weight: 8,
    language: "en",
  },
  {
    id: "yt-ben-awad",
    name: "Ben Awad",
    type: "youtube",
    category: "influencer-overseas",
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UC-8QAzbLcRglXeN_MY9blyw",
    channelId: "UC-8QAzbLcRglXeN_MY9blyw",
    weight: 6,
    language: "en",
  },
  // 블로그 인플루언서
  {
    id: "blog-dan-abramov",
    name: "Dan Abramov (overreacted)",
    type: "rss",
    category: "influencer-overseas",
    url: "https://overreacted.io/rss.xml",
    weight: 10,
    language: "en",
  },
  {
    id: "blog-kent-dodds",
    name: "Kent C. Dodds",
    type: "rss",
    category: "influencer-overseas",
    url: "https://kentcdodds.com/blog/rss.xml",
    weight: 9,
    language: "en",
  },
  {
    id: "blog-josh-comeau",
    name: "Josh W. Comeau",
    type: "rss",
    category: "influencer-overseas",
    url: "https://www.joshwcomeau.com/rss.xml",
    weight: 9,
    language: "en",
  },
  {
    id: "blog-lee-robinson",
    name: "Lee Robinson Blog",
    type: "rss",
    category: "influencer-overseas",
    url: "https://leerob.io/feed.xml",
    weight: 8,
    language: "en",
  },
  {
    id: "blog-tkdodo",
    name: "TkDodo (React Query)",
    type: "rss",
    category: "influencer-overseas",
    url: "https://tkdodo.eu/blog/rss.xml",
    weight: 8,
    language: "en",
  },
  {
    id: "blog-swyx",
    name: "swyx",
    type: "rss",
    category: "influencer-overseas",
    url: "https://www.swyx.io/rss.xml",
    weight: 7,
    language: "en",
  },
  {
    id: "blog-robin-wieruch",
    name: "Robin Wieruch",
    type: "rss",
    category: "influencer-overseas",
    url: "https://www.robinwieruch.de/index.xml",
    weight: 7,
    language: "en",
  },
  {
    id: "blog-mark-erikson",
    name: "Mark Erikson (Redux)",
    type: "rss",
    category: "influencer-overseas",
    url: "https://blog.isquaredsoftware.com/index.xml",
    weight: 7,
    language: "en",
  },
  {
    id: "blog-addy-osmani",
    name: "Addy Osmani",
    type: "rss",
    category: "influencer-overseas",
    url: "https://addyosmani.com/feed.xml",
    weight: 7,
    language: "en",
  },
  {
    id: "blog-syntax-fm",
    name: "Syntax.fm",
    type: "rss",
    category: "influencer-overseas",
    url: "https://feed.syntax.fm/rss",
    weight: 7,
    language: "en",
  },
  {
    id: "yt-developedbyed",
    name: "developedbyed",
    type: "youtube",
    category: "influencer-overseas",
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCD3KVjbb7aq2OiOffuungzw",
    channelId: "UCD3KVjbb7aq2OiOffuungzw",
    weight: 5,
    language: "en",
  },
  {
    id: "yt-james-q-quick",
    name: "James Q Quick",
    type: "youtube",
    category: "influencer-overseas",
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UC-T8W79DN6PBnzomelvqJYw",
    channelId: "UC-T8W79DN6PBnzomelvqJYw",
    weight: 6,
    language: "en",
  },
  {
    id: "yt-cosden",
    name: "Cosden Solutions",
    type: "youtube",
    category: "influencer-overseas",
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCMCcqbJpyL3LAv3PJeYz2bg",
    channelId: "UCMCcqbJpyL3LAv3PJeYz2bg",
    weight: 6,
    language: "en",
  },
  {
    id: "yt-sam-selikoff",
    name: "Sam Selikoff",
    type: "youtube",
    category: "influencer-overseas",
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCr8bI5LYCwMmkZVCFfwLBSg",
    channelId: "UCr8bI5LYCwMmkZVCFfwLBSg",
    weight: 6,
    language: "en",
  },
  {
    id: "blog-dmitri-pavlutin",
    name: "Dmitri Pavlutin",
    type: "rss",
    category: "influencer-overseas",
    url: "https://dmitripavlutin.com/rss.xml",
    weight: 6,
    language: "en",
  },
  {
    id: "blog-stefano-magni",
    name: "Stefano Magni",
    type: "rss",
    category: "influencer-overseas",
    url: "https://www.stefanomagni.com/rss.xml",
    weight: 5,
    language: "en",
  },
  {
    id: "blog-lydia-hallie",
    name: "Lydia Hallie",
    type: "rss",
    category: "influencer-overseas",
    url: "https://www.lydiahallie.com/feed.xml",
    weight: 7,
    language: "en",
  },
  {
    id: "yt-codevolution",
    name: "Codevolution",
    type: "youtube",
    category: "influencer-overseas",
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UC80PWRj_ZU8Zu0HSMNVwKWw",
    channelId: "UC80PWRj_ZU8Zu0HSMNVwKWw",
    weight: 5,
    language: "en",
  },
  {
    id: "yt-josh-tried",
    name: "Josh tried coding",
    type: "youtube",
    category: "influencer-overseas",
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCE_XmjRkHIoJ-a4NSqg2JOw",
    channelId: "UCE_XmjRkHIoJ-a4NSqg2JOw",
    weight: 6,
    language: "en",
  },
  {
    id: "blog-builder-io",
    name: "Builder.io Blog",
    type: "rss",
    category: "influencer-overseas",
    url: "https://www.builder.io/blog/rss.xml",
    weight: 7,
    language: "en",
  },
];
