import type { Source } from "./types.js";

export const influencersDomestic: Source[] = [
  {
    id: "blog-jbee",
    name: "JBEE (한재엽)",
    type: "rss",
    category: "influencer-domestic",
    url: "https://jbee.io/rss.xml",
    weight: 8,
    language: "ko",
  },
  {
    id: "blog-velopert",
    name: "velopert (김민준)",
    type: "rss",
    category: "influencer-domestic",
    url: "https://v2.velog.io/rss/velopert",
    weight: 8,
    language: "ko",
  },
  {
    id: "blog-teo",
    name: "테오의 프론트엔드",
    type: "rss",
    category: "influencer-domestic",
    url: "https://v2.velog.io/rss/teo",
    weight: 7,
    language: "ko",
  },
  {
    id: "blog-evan-moon",
    name: "Evan Moon",
    type: "rss",
    category: "influencer-domestic",
    url: "https://evan-moon.github.io/feed.xml",
    weight: 7,
    language: "ko",
  },
  {
    id: "blog-junilhwang",
    name: "황준일",
    type: "rss",
    category: "influencer-domestic",
    url: "https://junilhwang.github.io/TIL/rss.xml",
    weight: 6,
    language: "ko",
  },
  {
    id: "yt-nomad-coders",
    name: "노마드 코더",
    type: "youtube",
    category: "influencer-domestic",
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCUpJs89fSBXNolQGOYKn0YQ",
    channelId: "UCUpJs89fSBXNolQGOYKn0YQ",
    weight: 7,
    language: "ko",
  },
  {
    id: "yt-dream-coding",
    name: "드림코딩",
    type: "youtube",
    category: "influencer-domestic",
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UC_4u-bXaba7yrRz_6x6kb_w",
    channelId: "UC_4u-bXaba7yrRz_6x6kb_w",
    weight: 6,
    language: "ko",
  },
  {
    id: "yt-zerocho",
    name: "ZeroCho TV",
    type: "youtube",
    category: "influencer-domestic",
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCp-vBtwvBmDiGqjvLjChaJw",
    channelId: "UCp-vBtwvBmDiGqjvLjChaJw",
    weight: 7,
    language: "ko",
  },
  {
    id: "blog-kciter",
    name: "kciter (이선협)",
    type: "rss",
    category: "influencer-domestic",
    url: "https://kciter.so/feed.xml",
    weight: 7,
    language: "ko",
  },
  {
    id: "blog-hyunseob",
    name: "이현섭",
    type: "rss",
    category: "influencer-domestic",
    url: "https://hyunseob.github.io/atom.xml",
    weight: 6,
    language: "ko",
  },
  {
    id: "blog-daleseo",
    name: "DaleSeo",
    type: "rss",
    category: "influencer-domestic",
    url: "https://www.daleseo.com/rss.xml",
    weight: 6,
    language: "ko",
  },
  {
    id: "yt-codinggangss",
    name: "코딩앙마",
    type: "youtube",
    category: "influencer-domestic",
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCxft4RZ8lrK_BdPNz8NOP7Q",
    channelId: "UCxft4RZ8lrK_BdPNz8NOP7Q",
    weight: 5,
    language: "ko",
  },
  {
    id: "blog-toast-ui",
    name: "Toast UI Blog",
    type: "rss",
    category: "influencer-domestic",
    url: "https://ui.toast.com/rss",
    weight: 7,
    language: "ko",
  },
  // yt-latte-and-code 제거 — 채널 ID 무효 (YouTube RSS 404)

  {
    id: "blog-kakao-fe",
    name: "카카오 FE 기술블로그",
    type: "rss",
    category: "influencer-domestic",
    url: "https://tech.kakaoent.com/rss.xml",
    weight: 8,
    language: "ko",
  },
  {
    id: "blog-oliveyoung-tech",
    name: "올리브영 테크블로그",
    type: "rss",
    category: "influencer-domestic",
    url: "https://oliveyoung.tech/rss.xml",
    weight: 6,
    language: "ko",
  },
  // blog-channel-io 제거 — RSS 미제공
];
