import type { Source } from "./types.js";

export const newsletters: Source[] = [
  // bytes-dev 제거 — 공식 RSS 미제공
  {
    id: "tldr",
    name: "TLDR",
    type: "rss",
    category: "newsletter",
    url: "https://tldr.tech/api/rss/tech",
    weight: 7,
    language: "en",
  },
  {
    id: "javascript-weekly",
    name: "JavaScript Weekly",
    type: "rss",
    category: "newsletter",
    url: "https://javascriptweekly.com/rss",
    weight: 8,
    language: "en",
  },
  // react-newsletter 제거 — RSS 미제공 (이메일만)
  {
    id: "node-weekly",
    name: "Node Weekly",
    type: "rss",
    category: "newsletter",
    url: "https://nodeweekly.com/rss",
    weight: 6,
    language: "en",
  },
  {
    id: "css-weekly",
    name: "CSS Weekly",
    type: "rss",
    category: "newsletter",
    url: "https://feeds.feedburner.com/CSS-Weekly",
    weight: 6,
    language: "en",
  },
  {
    id: "frontend-focus",
    name: "Frontend Focus",
    type: "rss",
    category: "newsletter",
    url: "https://frontendfoc.us/rss",
    weight: 7,
    language: "en",
  },
  {
    id: "this-week-in-react",
    name: "This Week In React",
    type: "rss",
    category: "newsletter",
    url: "https://substack.thisweekinreact.com/feed",
    weight: 9,
    language: "en",
  },
  {
    id: "smashing-magazine",
    name: "Smashing Magazine",
    type: "rss",
    category: "newsletter",
    url: "https://www.smashingmagazine.com/feed/",
    weight: 7,
    language: "en",
  },
  {
    id: "css-tricks",
    name: "CSS-Tricks",
    type: "rss",
    category: "newsletter",
    url: "https://css-tricks.com/feed/",
    weight: 6,
    language: "en",
  },
  {
    id: "total-typescript",
    name: "Total TypeScript",
    type: "rss",
    category: "newsletter",
    url: "https://www.totaltypescript.com/rss.xml",
    weight: 8,
    language: "en",
  },
  // frontend-weekly-kr 제거 — SSL 인증서 문제
];
