import type { Source } from "./types.js";

export const newsletters: Source[] = [
  {
    id: "bytes-dev",
    name: "Bytes.dev",
    type: "rss",
    category: "newsletter",
    url: "https://bytes.dev/rss",
    weight: 8,
    language: "en",
  },
  {
    id: "tldr",
    name: "TLDR",
    type: "rss",
    category: "newsletter",
    url: "https://tldr.tech/api/rss/tech",
    weight: 7,
    language: "en",
  },
  {
    id: "javascript-weekly",
    name: "JavaScript Weekly",
    type: "rss",
    category: "newsletter",
    url: "https://javascriptweekly.com/rss",
    weight: 8,
    language: "en",
  },
  {
    id: "react-newsletter",
    name: "React Newsletter",
    type: "rss",
    category: "newsletter",
    url: "https://reactnewsletter.com/rss",
    weight: 8,
    language: "en",
  },
  {
    id: "node-weekly",
    name: "Node Weekly",
    type: "rss",
    category: "newsletter",
    url: "https://nodeweekly.com/rss",
    weight: 6,
    language: "en",
  },
  {
    id: "css-weekly",
    name: "CSS Weekly",
    type: "rss",
    category: "newsletter",
    url: "https://feeds.feedburner.com/CSS-Weekly",
    weight: 6,
    language: "en",
  },
  {
    id: "frontend-focus",
    name: "Frontend Focus",
    type: "rss",
    category: "newsletter",
    url: "https://frontendfoc.us/rss",
    weight: 7,
    language: "en",
  },
  {
    id: "this-week-in-react",
    name: "This Week In React",
    type: "rss",
    category: "newsletter",
    url: "https://thisweekinreact.com/rss",
    weight: 9,
    language: "en",
  },
  {
    id: "smashing-magazine",
    name: "Smashing Magazine",
    type: "rss",
    category: "newsletter",
    url: "https://www.smashingmagazine.com/feed/",
    weight: 7,
    language: "en",
  },
  {
    id: "css-tricks",
    name: "CSS-Tricks",
    type: "rss",
    category: "newsletter",
    url: "https://css-tricks.com/feed/",
    weight: 6,
    language: "en",
  },
  {
    id: "total-typescript",
    name: "Total TypeScript",
    type: "rss",
    category: "newsletter",
    url: "https://www.totaltypescript.com/rss.xml",
    weight: 8,
    language: "en",
  },
  {
    id: "frontend-weekly-kr",
    name: "프론트엔드 위클리",
    type: "rss",
    category: "newsletter",
    url: "https://frontendweekly.co/rss",
    weight: 7,
    language: "ko",
  },
];
